services:
  app:
    container_name: template_name-app
    image: template_name-app
    build:
      context: .
      args:
        - APP_ENV=dev
    command: [ "server:watch" ]
    volumes:
      - ./:/home/runner/work/hyperf-com-rapadura/hyperf-com-rapadura
    ports:
      - "9501:9501"
    environment:
      - SCAN_CACHEABLE=false
      - STDOUT_LOG_LEVEL=alert,critical,emergency,error,warning,notice,info
    networks:
      - template_name-network
    restart: on-failure

networks:
  template_name-network:
    name: template_name-network
