on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: hyperf/hyperf:8.3-alpine-v3.19-swoole
    steps:
      - uses: actions/checkout@v4

      - run: .docker/app/default.sh "UTC"

      - run: .docker/app/conditional.sh "test"

      - run: composer lint
