on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: hyperf/hyperf:8.3-alpine-v3.19-swoole
    steps:
      - uses: actions/checkout@v4

      - run: .docker/app/default.sh "UTC"

      - run: .docker/app/conditional.sh "test"

      - run: composer test

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
