on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      COMPOSE_RUNNER: "docker compose --compatibility"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: cp .github/ci/compose.override.yml compose.override.yml

      - run: make setup

      - run: make test

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
