on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      COMPOSE_RUNNER: "docker compose --compatibility"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: make setup

      - run: make test

      - run: |
          cp tests/.phpunit/logging.xml tests/logging.xml && \
          sed -i 's|/opt/www/tests/|${{ github.workspace }}/tests/|g' tests/logging.xml

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectBaseDir=${{ github.workspace }}
            -Dsonar.php.tests.reportPath=tests/logging.xml
