on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: devitools/hyperf:8.3-dev
      env:
        - SCAN_CACHEABLE=false
        - STDOUT_LOG_LEVEL=alert,critical,emergency,error,warning,notice,info
      options: --cpus 1

    services:
      postgres:
        profiles:
          - postgres
        container_name: template_name-postgres
        image: postgres:16.2
        tty: true
        env:
          - POSTGRES_USER=${POSTGRES_DB_USERNAME:-postgres}
          - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD:-root}
          - POSTGRES_DB=${POSTGRES_DB_NAME:-database}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: composer install

      - run: php bin/hyperf.php migrate

      - run: composer test

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.test.exclusions=tests/bootstrap.php
