on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      COMPOSE_RUNNER: "docker compose --compatibility"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - run: make setup

#      - run: make postgres

#      - run: make migrate

#      - run: make test

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.test.exclusions=tests/bootstrap.php
