on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:

      postgres:
        profiles:
          - postgres
        container_name: template_name-postgres
        image: postgres:16.2
        tty: true
        env:
          - POSTGRES_USER=${POSTGRES_DB_USERNAME:-postgres}
          - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD:-root}
          - POSTGRES_DB=${POSTGRES_DB_NAME:-database}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - '5432:5432'

    env:
      COMPOSE_RUNNER: "docker compose --compatibility"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

#      - run: make setup

#      - run: make postgres

#      - run: make migrate

#      - run: make test

      - uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.test.exclusions=tests/bootstrap.php
