on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    env:
      COMPOSE_RUNNER: "docker compose --compatibility"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git config --global --add safe.directory /__w/hyperf-com-rapadura/hyperf-com-rapadura

#      - run: make setup

#      - run: make postgres

#      - run: make migrate

#      - run: make test

      - run: sonar-scanner -Dsonar.host.url=https://sonarcloud.io
